CREATE DATABASE fcar CHAR SET utf8mb4
-- Liên quan đến Driver
-- T01_DRIVER_TYPE,  T02_ROLE, T03_ACCOUNT, T04_DRIVER, T05_DRIVER_DETAIL

-- Liên quan đến Customer
-- T06_GROUP, T07_CUSTOMER, T08_FEEDBACK, T09_COUPON

-- Liên quan đến Invoice
-- T10_PAYMENT_METHOD, T11_WALLET, T12_TRANSACTION, T13_TRANSACTION_DETAIL, T14_INVOICE, T15_INVOICE_DETAIL