-- Liên quan đến Driver
-- T01_DRIVER_TYPE,  T02_ROLE, T03_ACCOUNT, T04_DRIVER, T05_DRIVER_DETAIL
USE fcar;

-- disable foreign key check
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS T01_DRIVER_TYPE;
CREATE TABLE T01_DRIVER_TYPE(
	C01_DRIVER_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C01_DRIVER_TYPE_NAME VARCHAR(100) NOT NULL
);
DROP TABLE IF EXISTS T02_ROLE;
CREATE TABLE T02_ROLE(
	C02_ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C02_ROLE_NAME VARCHAR(255) NOT NULL
);
DROP TABLE IF EXISTS T03_ACCOUNT;
CREATE TABLE T03_ACCOUNT(
	C03_ACCOUNT_ID INT AUTO_INCREMENT PRIMARY KEY,
    C03_ACCOUNT_NAME VARCHAR(255) NOT NULL,
    C03_ACCOUNT_IDCARD VARCHAR(255),
    C03_ACCOUNT_PHONE VARCHAR(100) NOT NULL,
    C03_ACCOUNT_IMAGE VARCHAR(255),
    C03_ACCOUNT_EMAIL VARCHAR(255) NOT NULL,
    C03_ACCOUNT_PASSWORD VARCHAR(255) NOT NULL,
    C03_ACCOUNT_DOB DATE,
    C03_ACCOUNT_ADDRESS VARCHAR(255),
    C03_ROLE_ID INT NOT NULL,
    CONSTRAINT FK_T03_ACCOUNT_T02_ROLE FOREIGN KEY (C03_ROLE_ID) REFERENCES T02_ROLE(C02_ROLE_ID)
);

DROP TABLE IF EXISTS T04_DRIVER;
CREATE TABLE T04_DRIVER(
	C04_DRIVER_ID INT AUTO_INCREMENT PRIMARY KEY,
    C04_DRIVER_GPLX VARCHAR(100),
    C04_ACCOUNT_ID INT NOT NULL,
    CONSTRAINT FK_T04_DRIVER_T03_ACCOUNT FOREIGN KEY (C04_ACCOUNT_ID) REFERENCES T03_ACCOUNT(C03_ACCOUNT_ID)
);

CREATE TABLE T05_DRIVER_DETAIL(
	C05_DRIVER_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    C05_DRIVE_ID INT NOT NULL,
    C05_DRIVER_TYPE_ID INT NOT NULL,
    CONSTRAINT FK_T05_DRIVER_DETAIL_T04_DRIVER FOREIGN KEY (C05_DRIVE_ID) REFERENCES T04_DRIVER(C04_DRIVER_ID),
    CONSTRAINT FK_T05_DRIVER_DETAIL_T01_DRIVER_TYPE FOREIGN KEY (C05_DRIVER_TYPE_ID) REFERENCES T01_DRIVER_TYPE(C01_DRIVER_TYPE_ID)
);
USE fcar;
SET FOREIGN_KEY_CHECKS = 1;