-- Liên quan đến Customer
-- T06_GROUP, T07_CUSTOMER, T08_FEEDBACK, T09_COUPON

USE fcar;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS T06_GROUP;
CREATE TABLE T06_GROUP(
	C06_GROUP_ID INT AUTO_INCREMENT PRIMARY KEY,
    C06_GROUP_NAME VARCHAR(255)
);
DROP TABLE IF EXISTS T07_CUSTOMER;
CREATE TABLE T07_CUSTOMER(
	C07_CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    C07_CUSTOMER_POINT INT,
    C07_ACCOUNT_ID INT NOT NULL,
    C07_GROUP_ID INT NOT NULL,
    CONSTRAINT FK_T07_CUSTOMER_T03_ACCOUNT FOREIGN KEY (C07_ACCOUNT_ID) REFERENCES T03_ACCOUNT(C03_ACCOUNT_ID),
    CONSTRAINT FK_T07_CUSTOMER_T06_GROUP FOREIGN KEY (C07_GROUP_ID) REFERENCES T06_GROUP(C06_GROUP_ID)
);
DROP TABLE IF EXISTS T08_FEEDBACK;
CREATE TABLE T08_FEEDBACK(
	C08_FEEDBACK_ID INT AUTO_INCREMENT PRIMARY KEY,
    C08_FEEDBACK_CONTENT VARCHAR(255) NOT NULL,
    C08_FEEDBACK_CREATED_DATE DATE NOT NULL,
    C08_CUSTOMER_ID INT NOT NULL,
    C08_DRIVER_ID INT NOT NULL,
    CONSTRAINT FK_T08_FEEDBACK_T07_CUSTOMER FOREIGN KEY (C08_CUSTOMER_ID) REFERENCES T07_CUSTOMER(C07_CUSTOMER_ID),
    CONSTRAINT FK_T08_FEEDBACK_T04_DRIVERR FOREIGN KEY (C08_DRIVER_ID) REFERENCES T04_DRIVER(C04_DRIVER_ID)
);
DROP TABLE IF EXISTS T09_COUPON;
CREATE TABLE T09_COUPON(
	C09_COUPON_ID INT AUTO_INCREMENT PRIMARY KEY,
    C09_COUPON_NAME VARCHAR(255) NOT NULL,
    C09_COUPON_VALUE FLOAT NOT NULL,
    C09_COUPON_STATUS BIT(1),
    C09_CUSTOMER_ID INT NOT NULL,
    CONSTRAINT FK_T09_COUPON_T07_CUSTOMER FOREIGN KEY (C09_CUSTOMER_ID) REFERENCES T07_CUSTOMER(C07_CUSTOMER_ID)
);
SET FOREIGN_KEY_CHECKS = 1;