-- Liên quan đến Invoice
-- T10_PAYMENT_METHOD, T11_WALLET, T12_TRANSACTION, T13_TRANSACTION_DETAIL, T14_INVOICE, T15_INVOICE_DETAIL
USE fcar;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS T10_PAYMENT_METHOD;
CREATE TABLE T10_PAYMENT_METHOD(
	C10_PMETHOD_ID INT AUTO_INCREMENT PRIMARY KEY,
    C10_PMETHOD_DESC VARCHAR(255)
);
DROP TABLE IF EXISTS T11_WALLET;
CREATE TABLE T11_WALLET(
	C11_WALLET_ID INT AUTO_INCREMENT PRIMARY KEY,
    C11_WALLET_BALANCE FLOAT,
    C11_CREATE_AT DATE,
    C11_ACCOUNT_ID INT NOT NULL,
    CONSTRAINT FK_T11_WALLET_T03_ACCOUNT FOREIGN KEY (C11_ACCOUNT_ID) REFERENCES T03_ACCOUNT(C03_ACCOUNT_ID)
);
DROP TABLE IF EXISTS T12_TRANSACTION;
CREATE TABLE T12_TRANSACTION(
	C12_TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    C12_TRANSACTION_STATUS BIT(1),
    C12_CREATE_AT DATE,
    C12_WALLET_ID INT NOT NULL,
    CONSTRAINT FK_T12_TRANSACTION_T11_WALLET FOREIGN KEY (C12_WALLET_ID) REFERENCES T11_WALLET(C11_WALLET_ID)
);
DROP TABLE IF EXISTS T13_TRANSACTION_DETAIL;
CREATE TABLE T13_TRANSACTION_DETAIL(
	C13_TRANSACTION_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    C13_WALLET_ID INT NOT NULL,
    C13_TRANSACTION_ID INT NOT NULL,
    CONSTRAINT FK_T13_TRANSACTION_DETAIL_T11_WALLET 
									FOREIGN KEY (C13_WALLET_ID) REFERENCES T11_WALLET(C11_WALLET_ID),
    CONSTRAINT FK_T13_TRANSACTION_DETAIL_T12_TRANSACTION 
									FOREIGN KEY (C13_TRANSACTION_ID) REFERENCES T12_TRANSACTION(C12_TRANSACTION_ID)
);
DROP TABLE IF EXISTS T14_INVOICE;
CREATE TABLE T14_INVOICE(
	C14_INVOICE_ID INT AUTO_INCREMENT PRIMARY KEY,
    C14_BOOKING_DATE DATETIME NOT NULL,
    C14_STARTING_POINT VARCHAR(255) NOT NULL,
    C14_DESTINATION VARCHAR(255) NOT NULL,
    C14_ARRIVALTIME DATETIME NOT NULL,
    C14_INVOICE_STATUS BIT(1) NOT NULL,
    C14_DRIVER_ID INT NOT NULL,
    C14_TRANSACTION_ID INT NOT NULL,
    C14_PMETHOD_ID INT NOT NULL,
    CONSTRAINT FK_T14_INVOICE_T12_TRANSACTION 
									FOREIGN KEY (C14_TRANSACTION_ID) REFERENCES T12_TRANSACTION(C12_TRANSACTION_ID),
	CONSTRAINT FK_T14_INVOICE_T04_DRIVER 
									FOREIGN KEY (C14_DRIVER_ID) REFERENCES T04_DRIVER(C04_DRIVER_ID),
    CONSTRAINT FK_T14_INVOICE_T10_PAYMENT_METHOD 
									FOREIGN KEY (C14_PMETHOD_ID) REFERENCES T10_PAYMENT_METHOD (C10_PMETHOD_ID)                                
                                    
);
DROP TABLE IF EXISTS T15_INVOICE_DETAIL;
CREATE TABLE T15_INVOICE_DETAIL(
	C15_INVOICE_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    C15_INVOICE_ID INT NOT NULL,
    C15_CUSTOMER_ID INT NOT NULL,
    CONSTRAINT FK_T15_INVOICE_DETAIL_T14_INVOICE 
									FOREIGN KEY (C15_INVOICE_ID) REFERENCES T14_INVOICE (C14_INVOICE_ID),
    CONSTRAINT FK_T15_INVOICE_DETAIL_T07_CUSTOMER
									FOREIGN KEY (C15_CUSTOMER_ID) REFERENCES T07_CUSTOMER (C07_CUSTOMER_ID)                                
);
SET FOREIGN_KEY_CHECKS = 1;